"use client";

import { motion } from "framer-motion";
import { Scale, ShieldCheck, Eye, Lock, GitMerge } from "lucide-react";

export default function EthicsPage() {
  return (
    <div className="absolute inset-0 overflow-y-auto custom-scrollbar bg-background p-10">
      <div className="max-w-4xl mx-auto z-10 relative mt-10 pb-20">
        <div className="mb-16 border-b border-border/50 pb-8">
          <p className="font-display text-primary uppercase tracking-widest text-sm font-bold mb-3 flex items-center gap-2">
            <Scale className="w-4 h-4" /> Corporate Governance
          </p>
          <h1 className="text-6xl font-bold text-foreground font-display tracking-tight mb-6">Ethics & Transparency</h1>
          <p className="text-xl text-foreground leading-relaxed max-w-3xl">
            VarshaAI operates on the fundamental principle that planetary-scale intelligence must be auditable, unbiased, and rigorously governed. 
            Our neural networks make decisions that impact millions; transparency is not optional—it is operational protocol.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
          <div className="os-card p-8 bg-background border-border/50 hover:border-primary/50 transition-colors">
            <ShieldCheck className="w-8 h-8 text-tertiary mb-6" />
            <h3 className="text-xl font-bold text-foreground mb-3">Unbiased Forecasting</h3>
            <p className="text-muted-foreground leading-relaxed">
              Our models are rigorously trained to prevent socioeconomic bias in disaster resource allocation. Predictive metrics are evaluated strictly on atmospheric physics, not demographic weighting.
            </p>
          </div>
          
          <div className="os-card p-8 bg-background border-border/50 hover:border-primary/50 transition-colors">
            <Eye className="w-8 h-8 text-primary mb-6" />
            <h3 className="text-xl font-bold text-foreground mb-3">Model Interpretability</h3>
            <p className="text-muted-foreground leading-relaxed">
              We employ advanced Explainable AI (XAI) pipelines. Every trajectory prediction generated by the neural net is accompanied by a feature-importance matrix, ensuring operators understand the "why" behind the forecast.
            </p>
          </div>

          <div className="os-card p-8 bg-background border-border/50 hover:border-primary/50 transition-colors">
            <Lock className="w-8 h-8 text-chart-3 mb-6" />
            <h3 className="text-xl font-bold text-foreground mb-3">Data Privacy</h3>
            <p className="text-muted-foreground leading-relaxed">
              Telemetry ingested from civil infrastructure is strictly anonymized. VarshaAI complies with global data protection frameworks, operating entirely within secured national datacenters.
            </p>
          </div>

          <div className="os-card p-8 bg-background border-border/50 hover:border-primary/50 transition-colors">
            <GitMerge className="w-8 h-8 text-error mb-6" />
            <h3 className="text-xl font-bold text-foreground mb-3">Open-Source Audits</h3>
            <p className="text-muted-foreground leading-relaxed">
              Our core decision-making algorithms are subjected to independent, third-party code audits bi-annually. Critical non-classified logic is available for scientific peer review.
            </p>
          </div>
        </div>

        <div className="os-card p-8 bg-muted/30 border-l-[3px] border-l-[#3cd7ff]">
          <h2 className="text-2xl font-bold text-foreground mb-4">The VarshaAI Prime Directive</h2>
          <p className="text-foreground leading-relaxed mb-4">
            "To accurately model the fluid dynamics of the Earth's atmosphere for the preservation of human life and infrastructure, prioritizing actionable intelligence over opaque complexity."
          </p>
          <button className="px-4 py-2 mt-4 bg-muted border border-primary/30 text-primary text-sm font-bold uppercase tracking-widest hover:bg-primary/10 transition-colors">
            Download Transparency Report 2026.Q2
          </button>
        </div>
      </div>
    </div>
  );
}
