"""Initial schema

Revision ID: fb276a4404e6
Revises: 
Create Date: 2026-07-19 01:53:36.177494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb276a4404e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('time_horizon', sa.String(), nullable=False),
    sa.Column('predicted_rainfall', sa.Float(), nullable=True),
    sa.Column('predicted_temp', sa.Float(), nullable=True),
    sa.Column('heatwave_risk', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_id'), 'prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_state'), 'prediction_logs', ['state'], unique=False)
    op.create_table('simulation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_offset', sa.Float(), nullable=False),
    sa.Column('rainfall_multiplier', sa.Float(), nullable=False),
    sa.Column('humidity_offset', sa.Float(), nullable=False),
    sa.Column('wind_multiplier', sa.Float(), nullable=False),
    sa.Column('flood_risk', sa.String(), nullable=False),
    sa.Column('drought_risk', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_records_id'), 'simulation_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_records_id'), table_name='simulation_records')
    op.drop_table('simulation_records')
    op.drop_index(op.f('ix_prediction_logs_state'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    # ### end Alembic commands ###
