"use client";

import { motion } from "framer-motion";
import { FileText, FileWarning } from "lucide-react";

export default function LegalPage() {
  return (
    <div className="absolute inset-0 overflow-y-auto custom-scrollbar bg-background p-10">
      <div className="max-w-4xl mx-auto z-10 relative mt-10 pb-20">
        <div className="mb-16 border-b border-border/50 pb-8">
          <p className="font-display text-muted-foreground uppercase tracking-widest text-sm font-bold mb-3 flex items-center gap-2">
            <FileText className="w-4 h-4" /> Legal & Compliance
          </p>
          <h1 className="text-6xl font-bold text-foreground font-display tracking-tight mb-6">Terms of Service</h1>
          <p className="text-xl text-foreground leading-relaxed max-w-3xl">
            This document outlines the legal framework and liability limitations governing the use of the VarshaAI Planetary Operating System.
          </p>
        </div>
        
        <div className="os-card p-8 bg-error/5 border-error/30 mb-12 flex items-start gap-4">
          <FileWarning className="w-6 h-6 text-error flex-shrink-0 mt-1" />
          <div>
            <h3 className="text-xl font-bold text-foreground mb-2">Critical Life-Safety Disclaimer</h3>
            <p className="text-error/80 leading-relaxed">
              VarshaAI is a predictive modeling tool designed to supplement, not replace, official governmental emergency broadcast systems. 
              In the event of a severe weather crisis, always defer to the immediate instructions of local emergency management agencies. 
              VarshaAI Planetary Systems assumes no liability for actions taken based solely on AI-generated predictive trajectories.
            </p>
          </div>
        </div>

        <div className="space-y-12 text-foreground leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">1. Data Usage & Intellectual Property</h2>
            <p className="mb-4">
              All planetary models, algorithms, UI designs, and predictive data generated by the VarshaAI system remain the exclusive intellectual property of VarshaAI Planetary Systems. 
              Users are granted a limited, non-exclusive license to utilize the API and dashboard for internal analytics and operational planning.
            </p>
            <p>
              Redistribution of raw telemetry data or reverse-engineering of the core neural net architecture is strictly prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">2. Service Level Agreement (SLA)</h2>
            <p className="mb-4">
              VarshaAI strives for a 99.999% uptime for critical forecasting infrastructure. However, as the system relies on orbital satellite telemetry which may be subject to solar interference or orbital debris strikes, momentary interruptions in live data feeds may occur.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">3. Privacy Policy</h2>
            <p className="mb-4">
              We process minimal personal identifiable information (PII). Any operator data collected is utilized strictly for authentication, security auditing, and system performance telemetry. 
              VarshaAI complies with all modern data protection regulations including GDPR and regional equivalents.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
